name: sadra_at
description: Sadra.at main page
homepage: https://sadra.at

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.20
  http: ^0.13.4
  google_fonts: ^2.1.0
  intl: ^0.17.0
  just_audio: ^0.9.18
  bloc: ^8.0.1
  equatable: ^2.0.3
  fake_async: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4


flutter:
  generate: true
  uses-material-design: true


  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
